name: contao-database-backup

services:
    appserver:
        type: php:8.2
        via: cli

tooling:
    composer:
        service: appserver
        cmd: composer

    ecs:
        service: appserver
        cmd: composer ecs
