services:
    bwein.database_backup.listener.cronjob:
        class: Bwein\DatabaseBackup\EventListener\CronjobListener
        arguments:
        - '@contao.framework'
        - '@bwein.database_backup.dumper'
        - '@logger'
        tags:
        - { name: 'monolog.logger', channel: 'bwein_database_backup' }
        public: true

    bwein.database_backup.listener.navigation:
        class: Bwein\DatabaseBackup\EventListener\NavigationListener
        arguments:
        - '@request_stack'
        - '@router'
        - '@translator'
        - '@contao.framework'
        public: true
