services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $backupManager: '@contao.doctrine.backup_manager'

    Bwein\DatabaseBackup\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Resources}'

    bwein.database_backup.dumper:
        alias: Bwein\DatabaseBackup\Service\DatabaseBackupDumper
        deprecated: 'The "%alias_id%" alias is deprecated. Do not use it anymore.'

