services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $backupManager: '@contao.doctrine.backup_manager'

    Bwein\DatabaseBackup\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Resources}'
