services:
    _defaults:
        autowire: true
        autoconfigure: true

    Bwein\DatabaseBackup\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Resources}'

    bwein.database_backup.dumper:
        alias: Bwein\DatabaseBackup\Service\DatabaseBackupDumper
        deprecated: 'The "%alias_id%" alias is deprecated. Do not use it anymore.'

    bwein.database_backup.dump_command:
        alias: Bwein\DatabaseBackup\Command\DatabaseBackupCommand
        deprecated: 'The "%alias_id%" alias is deprecated. Do not use it anymore.'
